apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: production
  name: mysql-pvc
spec:
  storageClassName: ""
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteOnce
