apiVersion: v1
kind: Pod
metadata:
  name: blue-pod-simple-webapp-color
  labels:
    app: web
  namespace: production
spec:
  containers:
    - name: simple-webapp-color
      image: mmumshad/simple-webapp-color
      env:
        - name: APP_COLOR
          value: blue